### ISSUE TITLE
Custom MQTT Topic

### ISSUE THREAD

**Issue by niklaswall** [jdomeij/H801_MQTT#2]
This is a really amazing firmware! :+1: 

I do however miss the possibility to define a custom topic instead of the built-in ID.

Preferably it would be great if you could define your own custom topic that will be used instead of the device ID... it would however also be nice if it still listened to commands on the ID so there is a fallback topic available that is always unique.

Is it possible to add that functionality?

Keep it up!
/Niklas

**Comment by jdomeij** [comment]
This can be controlled by setting the `mqtt_alias` keyword, the device will still listen to set commands to the built-in ID topic
